"""empty message

Revision ID: 445739d44f2f
Revises: e2fa62121621
Create Date: 2023-12-14 12:30:36.051306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '445739d44f2f'
down_revision: Union[str, None] = 'e2fa62121621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the existing primary key constraint
    op.drop_constraint('papertrades_pkey', 'papertrades', type_='primary')
    # Drop the existing 'id' column
    op.drop_column('papertrades', 'id')
    # Add a new primary key constraint on 'pair_address'
    op.create_primary_key('pk_papertrades', 'papertrades', ['pair_address'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the primary key constraint on 'pair_address'
    op.drop_constraint('pk_papertrades', 'papertrades', type_='primary')
    # Add the 'id' column back
    op.add_column('papertrades', sa.Column('id', sa.Integer(), nullable=False))
    # Add a new primary key constraint on 'id'
    op.create_primary_key('papertrades_pkey', 'papertrades', ['id'])
    # ### end Alembic commands ###
