"""empty message

Revision ID: 990e46c0e1ae
Revises: 07b14fd6ab53
Create Date: 2023-11-13 23:24:07.543717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '990e46c0e1ae'
down_revision: Union[str, None] = '07b14fd6ab53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('newpairs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newpairs', sa.Column(
        'dexscreener_data_updated_at', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
