"""empty message

Revision ID: aeb572af7af2
Revises: 445739d44f2f
Create Date: 2023-12-14 12:57:29.777052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aeb572af7af2'
down_revision: Union[str, None] = '445739d44f2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add foreign key constraint to 'pair_address' in 'papertrades'
    op.create_foreign_key(
        'fk_papertrades_pair_address_newpairs',
        'papertrades', 'newpairs',
        ['pair_address'], ['pair_address']
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove foreign key constraint from 'pair_address' in 'papertrades'
    op.drop_constraint(
        'fk_papertrades_pair_address_newpairs',
        'papertrades',
        type_='foreignkey'
    )
    # ### end Alembic commands ###
