"""empty message

Revision ID: b2aa5f9f0683
Revises: aeb572af7af2
Create Date: 2023-12-15 20:07:58.288876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2aa5f9f0683'
down_revision: Union[str, None] = 'aeb572af7af2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historicpairs',
                    sa.Column('pair_address', sa.String(
                        length=50), nullable=False),
                    sa.Column('created_at', sa.Integer(), nullable=True),
                    sa.Column('initial_scan_data', sa.JSON(), nullable=True),
                    sa.Column('later_scan_data', sa.JSON(), nullable=True),
                    sa.Column('is_verified', sa.Boolean(), nullable=True),
                    sa.Column('is_locked', sa.Boolean(), nullable=True),
                    sa.Column('is_renounced', sa.Boolean(), nullable=True),
                    sa.Column('in_dex', sa.Boolean(), nullable=True),
                    sa.Column('in_dex_time', sa.JSON(), nullable=True),
                    sa.Column('socials_data', sa.JSON(), nullable=True),
                    sa.Column('goplus_data', sa.JSON(), nullable=True),
                    sa.Column('honeypot_data', sa.JSON(), nullable=True),
                    sa.Column('gecko_chart_data', sa.JSON(), nullable=True),
                    sa.Column('dexscreener_data', sa.JSON(), nullable=True),
                    sa.Column('lock_data', sa.JSON(), nullable=True),
                    sa.Column('ohlcv_data', sa.JSON(), nullable=True),
                    sa.Column('is_honeypot', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('pair_address')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historicpairs')
    # ### end Alembic commands ###
