"""empty message

Revision ID: dca1043624b8
Revises: 553478bc1527
Create Date: 2023-12-03 22:25:12.656252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dca1043624b8'
down_revision: Union[str, None] = '553478bc1527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pairtrades')
    op.drop_table('newpairs')
    # ### end Alembic commands ###


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papertrades',
                    sa.Column('id', sa.Integer, primary_key=True),
                    sa.Column('pair_address', sa.String(
                        length=50), nullable=False),
                    sa.Column('created_at', sa.Integer, nullable=False),
                    sa.Column('trade_details', sa.JSON, nullable=True),
                    sa.ForeignKeyConstraint(
                        ['pair_address'], ['newpairs.pair_address']),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('papertrades')
    # ### end Alembic commands ###
